version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install aws-sam-cli -q

  build:
    commands:
      - echo "Running sam package..."
      - sam package
          --template-file samTemplate.yml
          --s3-bucket anton-karmanov-codebuild-artifacts
          --s3-prefix sam-artifacts
          --output-template-file outputSamTemplate.yml
          --region eu-north-1

artifacts:
  files:
    - outputSamTemplate.yml
